config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/pynblint
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test:
      branch: main
      repo: https://gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test git:
        commands:
        - /usr/bin/env sh .sqa/script.messy-tomato-dingo.sh
        container: qc.acc_stinky-mauve-giraffe
  QC.Doc:
    repos:
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-black-hare.sh
        container: qc.doc_foggy-platinum-maltese
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test git:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-persimmon-caterpillar.sh
        container: qc.doc_scummy-champagne-dane
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-yellow-frise.sh
        container: qc.doc_shaky-dandelion-insect
  QC.Lic:
    repos:
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test licensee:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-corn-goat.sh
        container: qc.lic_lumpy-zucchini-wolf
  QC.Sec:
    repos:
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test bandit:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-sapphire-bobcat.sh
        container: qc.sec_gummy-platinum-rattlesnake
  QC.Sty:
    repos:
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test pynblint.py:
        commands:
        - /usr/bin/env sh .sqa/script.homey-pumpkin-woodlouse.sh
        container: qc.sty_snazzy-black-opossum
  QC.Uni:
    repos:
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test pytest:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-linen-impala.sh
        container: qc.uni_jumpy-fuchsia-sponge
  QC.Ver:
    repos:
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.messy-platinum-spaniel.sh
        container: qc.ver_tasty-teal-olm
timeout: 5400
