config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/pynblint
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test:
      branch: main
      repo: https://gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test git:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-ultramarine-akbash.sh
        container: qc.acc_goopy-cerise-chihuahua
  QC.Doc:
    repos:
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-flax-echidna.sh
        container: qc.doc_snappy-yellow-moth
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test git:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-seashell-lemming.sh
        container: qc.doc_lumpy-cobalt-dunker
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-cream-manatee.sh
        container: qc.doc_shaky-sepia-lemming
  QC.Lic:
    repos:
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test licensee:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-flax-mist.sh
        container: qc.lic_chewy-myrtle-giraffe
  QC.Sec:
    repos:
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test bandit:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-zucchini-newt.sh
        container: qc.sec_hasty-cream-oyster
  QC.Sty:
    repos:
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test pynblint.py:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-salmon-numbat.sh
        container: qc.sty_boozy-ecru-cheetah
  QC.Uni:
    repos:
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test pytest:
        commands:
        - /usr/bin/env sh .sqa/script.surly-zucchini-mist.sh
        container: qc.uni_cloudy-sangria-cheetah
  QC.Ver:
    repos:
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-aquamarine-hound.sh
        container: qc.ver_nerdy-white-akbash
timeout: 5400
