config:
  credentials:
  - id: https://gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test
    password_var: gAAAAABpaKEdi3ZnPQAM86lgoR4N-jSV1HfQgqLFitetyaVvSPlR1iHZJKx0lkBFkPsfdJIBwK6ucCNT4vGNuVSoZawK51RY1cgUFrUlNe5icZbKKOirliVAMeZFoC_9ZMIaPN-hxl9K
    username_var: gAAAAABpaKEdfaVyRU95uXTwPpeHChM88VaZK8zu9UbHjRoQi75Vhf6uWwpwfOJpzCAW6-r4uzxB7tiTm3_6anlfwpzKak-3OQ==
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/pynblint
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test:
      branch: main
      credential_tmp: true
      repo: https://gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test git:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-maroon-ocelot.sh
        container: qc.acc_shabby-sangria-whippet
  QC.Doc:
    repos:
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-thistle-iguana.sh
        container: qc.doc_gloppy-white-affenpinscher
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test git:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-lavender-buffalo.sh
        container: qc.doc_squeaky-silver-bullfrog
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-lavender-kudu.sh
        container: qc.doc_tacky-alizarin-orangutan
  QC.Lic:
    repos:
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test licensee:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-jade-mongrel.sh
        container: qc.lic_crabby-black-lemming
  QC.Sec:
    repos:
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test bandit:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-olive-giraffe.sh
        container: qc.sec_fuzzy-pear-newfoundland
  QC.Sty:
    repos:
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test pynblint.py:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-firebrick-nightingale.sh
        container: qc.sty_gloppy-cerulean-wolverine
  QC.Uni:
    repos:
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test pytest:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-yellow-bullfrog.sh
        container: qc.uni_fuzzy-peach-bombay
  QC.Ver:
    repos:
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-pink-elephant.sh
        container: qc.ver_muzzy-firebrick-tarsier
timeout: 5400
