config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/pynblint
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test:
      branch: main
      repo: https://gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test git:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-eggplant-meerkat.sh
        container: qc.acc_snazzy-denim-shark
  QC.Doc:
    repos:
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-gold-macaque.sh
        container: qc.doc_droopy-crimson-loon
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test git:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-chocolate-skunk.sh
        container: qc.doc_stinky-cerulean-albatross
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-rose-kangaroo.sh
        container: qc.doc_homely-ultramarine-rabbit
  QC.Lic:
    repos:
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test licensee:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-linen-dolphin.sh
        container: qc.lic_pokey-heliotrope-shrimp
  QC.Sec:
    repos:
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test bandit:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-harlequin-shark.sh
        container: qc.sec_stinky-grey-tamarin
  QC.Sty:
    repos:
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test flake8:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-fuchsia-lion.sh
        container: qc.sty_messy-plum-panda
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.randy-emerald-chinook.sh
        container: qc.sty_gummy-ivory-gharial
  QC.Uni:
    repos:
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test pytest:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-aqua-raccoon.sh
        container: qc.uni_wiggy-salmon-chin
  QC.Ver:
    repos:
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-black-toucan.sh
        container: qc.ver_squirrely-peach-affenpinscher
timeout: 5400
