config:
  credentials:
  - id: https://gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test
    password_var: gAAAAABpaJ1oYwZ79GNAB1HHMVPkbtYRgPeDuyQ2PvdhcV343X2YoVJwXeMNgDPwWw2js9F9Oifq_whTFwt8bkmFK_MMkDxVQYzEzEoFWUmQY_yFejw3QwEMYQYNpBuBq-RxkJr3gvHU
    username_var: gAAAAABpaJ1odJq7f68RU1fqIWdc72GrZ1WwBSUYRLSoGQZ4pLUtE4hiKm_h8CNbdDvAdK5yv8U5rkdyvP4d5f03NDffOwTPtw==
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/pynblint
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test:
      branch: main
      credential_tmp: true
      repo: https://gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test git:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-russet-millipede.sh
        container: qc.acc_hilly-xanthic-ibis
  QC.Doc:
    repos:
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.ready-jade-caracal.sh
        container: qc.doc_leaky-platinum-pinscher
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test git:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-linen-lionfish.sh
        container: qc.doc_homely-smalt-stoat
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-mustard-robin.sh
        container: qc.doc_homey-saffron-bongo
  QC.Lic:
    repos:
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test licensee:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-tomato-dollar.sh
        container: qc.lic_cozy-goldenrod-uakari
  QC.Sec:
    repos:
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test bandit:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-linen-camel.sh
        container: qc.sec_grumpy-celadon-gopher
  QC.Sty:
    repos:
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test pynblint.py:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-buff-quail.sh
        container: qc.sty_skinny-olive-toucan
  QC.Uni:
    repos:
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test pytest:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-persimmon-chamois.sh
        container: qc.uni_sleepy-corn-eel
  QC.Ver:
    repos:
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-sangria-bee.sh
        container: qc.ver_stinky-copper-albatross
timeout: 5400
