config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/pynblint
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test:
      branch: main
      repo: https://gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test git:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-pumpkin-centipede.sh
        container: qc.acc_scummy-carmine-collie
  QC.Doc:
    repos:
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-chestnut-affenpinscher.sh
        container: qc.doc_fuzzy-pear-frigatebird
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test git:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-red-grasshopper.sh
        container: qc.doc_gimpy-cobalt-wolfhound
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-apricot-hound.sh
        container: qc.doc_whiny-cinnamon-pinscher
  QC.Lic:
    repos:
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test licensee:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-maroon-malamute.sh
        container: qc.lic_frumpy-platinum-fish
  QC.Sec:
    repos:
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test bandit:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-brass-dachsbracke.sh
        container: qc.sec_skanky-champagne-fish
  QC.Sty:
    repos:
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test pynblint.py:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-lavender-zebu.sh
        container: qc.sty_muzzy-charcoal-mongrel
  QC.Uni:
    repos:
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test pytest:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-pear-ray.sh
        container: qc.uni_flimsy-red-squirt
  QC.Ver:
    repos:
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-orchid-snail.sh
        container: qc.ver_stuffy-bronze-kiwi
timeout: 5400
