config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/pynblint
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test:
      branch: main
      repo: https://gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test git:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-mustard-javanese.sh
        container: qc.acc_gummy-vermilion-beetle
  QC.Doc:
    repos:
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-corn-caterpillar.sh
        container: qc.doc_silly-champagne-antelope
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test git:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-celadon-mole.sh
        container: qc.doc_silly-ruby-crocodile
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-azure-skunk.sh
        container: qc.doc_hilly-maroon-bird
  QC.Lic:
    repos:
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-lime-peccary.sh
        container: qc.lic_sloppy-jade-leopard
  QC.Sec:
    repos:
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test bandit:
        commands:
        - /usr/bin/env sh .sqa/script.ready-cobalt-ragdoll.sh
        container: qc.sec_skinny-viridian-malamute
  QC.Sty:
    repos:
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test pynblint.py:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-corn-labradoodle.sh
        container: qc.sty_seedy-emerald-drever
  QC.Uni:
    repos:
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test pytest:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-bistre-chow.sh
        container: qc.uni_tacky-eggplant-termite
  QC.Ver:
    repos:
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-orchid-mist.sh
        container: qc.ver_stealthy-fuchsia-walrus
timeout: 5400
