config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/pynblint
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test:
      branch: main
      repo: https://gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test git:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-rust-quetzal.sh
        container: qc.acc_geeky-sangria-dunker
  QC.Doc:
    repos:
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-linen-hummingbird.sh
        container: qc.doc_fuzzy-ochre-whippet
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test git:
        commands:
        - /usr/bin/env sh .sqa/script.surly-aquamarine-mouse.sh
        container: qc.doc_snappy-teal-woodpecker
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-pear-molly.sh
        container: qc.doc_nippy-cardinal-chin
  QC.Lic:
    repos:
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test licensee:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-mustard-orangutan.sh
        container: qc.lic_slaphappy-chartreuse-russel
  QC.Sec:
    repos:
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test bandit:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-lime-jaguar.sh
        container: qc.sec_breezy-smalt-hyrax
  QC.Sty:
    repos:
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test flake8:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-pear-cougar.sh
        container: qc.sty_baggy-chocolate-bear
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-mustard-sponge.sh
        container: qc.sty_leaky-emerald-leopard
  QC.Uni:
    repos:
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test pytest:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-cream-dragonfly.sh
        container: qc.uni_flaky-white-deer
  QC.Ver:
    repos:
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-zucchini-mongrel.sh
        container: qc.ver_whiny-red-schnauzer
timeout: 5400
